services:
 database:
  image: postgres:16
  container_name: db_postgres
  environment:
   POSTGRES_USER: admin
   POSTGRES_PASSWORD: admin123
   POSTGRES_DB: coinflow
  ports:
   - 5434:5432
  volumes:
   - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
   - pg_fresh_data:/var/lib/postgresql/data
  networks:
   - my_network
volumes:
 pg_fresh_data:

networks:
 my_network:
   driver: bridge