version: 2

sources:
  - name: coins_raw
    schema: raw
    description: raw crypo currency data of each coin in the market

    tables:
    - name: coin_markets
    - description: raw crypo currency market data of each coin in the market

models:
  - name: stg_coin_markets
    description: staged crypo currency market data of each coin in the market

    config:
      materialized: table
      description: staged crypo currency market data of each coin in the market