version: 2

models:
  - name: int_coin_daily_metrics
    description: intermediate model that calculates daily price change % and 7-day moving average for each coin; serves as a source for final reporting models.

    config:
      materialized: table
    columns:
      - name: coin_id
        description: unique identifier for each coin
      - name: date_stamp
        description: timestamp of the price record
      - name: name_of_coin
        description: name of the coin
      - name: open_price
        description: opening price of the coin for the day
      - name: close_price
        description: closing price of the coin for the day
      - name: high_price
        description: highest price of the coin for the day
      - name: low_price
        description: lowest price of the coin for the day
      - name: close_market_cap
        description: market capitalization of the coin at the close of the day
      - name: close_total_volume
        description: total trading volume of the coin at the close of the day
      - name: prev_day_price
        description: closing price of the coin from the previous day
      - name: daily_price_change_pcg
        description: percentage change in price from the previous day to the current day
      - name: moving_avg_7d
        description: 7-day moving average of the closing price for the coin
    