version: 2

sources:
  - name: history_coins_raw
    schema: raw
    description: raw crypo currency history data of each coin in the market for the past 90 days

    tables:
    - name: coin_price_history
    description: raw crypo currency price history data of each coin in the market for the past 90 days

models:
  - name: stg_coin_price_history
    description: staged crypo currency price history and coin market data of each coin in the market

    config:
      materialized: table
      description: staged crypo currency price history and coin market data of each coin in the market
      